package com.backend.IMonitoring.service;

import com.backend.IMonitoring.dto.UserDTO;
import com.backend.IMonitoring.model.User;
import com.backend.IMonitoring.model.Rol;
import com.backend.IMonitoring.repository.UserRepository;
import com.backend.IMonitoring.repository.ReservationRepository;
import com.backend.IMonitoring.exceptions.UnauthorizedAccessException;
import com.backend.IMonitoring.exceptions.ResourceNotFoundException;
import com.backend.IMonitoring.exceptions.UserAlreadyExistsException;
import com.backend.IMonitoring.exceptions.InvalidCredentialsException;
import com.backend.IMonitoring.utils.CareerUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Sort;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class UserService {
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final ReservationRepository reservationRepository;
    private final EmailService emailService;

    private final AuditLogService auditLogService;

    public List<User> getAllUsers() {
        return userRepository.findAll(Sort.by(Sort.Direction.ASC, "name"));
    }

    public User getUserById(String id) {
        return userRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Usuario no encontrado con ID: " + id));
    }

    public List<User> getUsersByRole(Rol role) {
        return userRepository.findByRole(role, Sort.by(Sort.Direction.ASC, "name"));
    }

    @Transactional
    public User createUser(UserDTO userDTO, User performingUser) {
        if (performingUser != null) {
            if (performingUser.getRole() == Rol.COORDINADOR) {
                if (userDTO.getRole() != Rol.ESTUDIANTE && userDTO.getRole() != Rol.PROFESOR && userDTO.getRole() != Rol.TUTOR) {
                    throw new UnauthorizedAccessException("Los Coordinadores solo pueden crear cuentas de Estudiante, Profesor o Tutor.");
                }
                if (performingUser.getCareer() == null) {
                    throw new UnauthorizedAccessException("Tu cuenta de Coordinador no tiene una carrera asignada.");
                }
                if (userDTO.getCareer() == null || userDTO.getCareer().isEmpty()) {
                    userDTO.setCareer(performingUser.getCareer());
                } else {
                    if (!CareerUtils.areSameCareerGroup(performingUser.getCareer(), userDTO.getCareer())) {
                        throw new UnauthorizedAccessException("No puedes asignar la carrera '" + userDTO.getCareer() + "' porque no pertenece a tu grupo académico.");
                    }
                }
            }
            else if (performingUser.getRole() == Rol.ADMIN) {
                if (userDTO.getRole() == Rol.COORDINADOR && (userDTO.getCareer() == null || userDTO.getCareer().isEmpty())) {
                    throw new IllegalArgumentException("Al crear un Coordinador, debes asignarle una carrera.");
                }
            }
            else {
                throw new UnauthorizedAccessException("No tienes permiso para crear usuarios.");
            }
        }

        String rawPassword = userDTO.getPassword();
        boolean autoGenerated = false;

        if (rawPassword == null || rawPassword.trim().isEmpty()) {
            if (userDTO.getEmail() != null && userDTO.getEmail().contains("@")) {
                String baseName = userDTO.getEmail().split("@")[0].toLowerCase();
                int currentYearTwoDigits = java.time.Year.now().getValue() % 100;
                rawPassword = baseName + currentYearTwoDigits;
                autoGenerated = true;
            } else {
                throw new IllegalArgumentException("Correo inválido para generar contraseña.");
            }
        }

        User user = userDTO.toEntity();
        user.setCareer(userDTO.getCareer());
        user.setPassword(rawPassword);

        return createUserEntityLogic(user, rawPassword, autoGenerated, performingUser);
    }

    @Transactional
    protected User createUserEntityLogic(User user, String rawPassword, boolean isAutoGenerated, User performingUser) {
        if (userRepository.findByEmail(user.getEmail()).isPresent()) {
            throw new UserAlreadyExistsException("El correo electrónico '" + user.getEmail() + "' ya está registrado.");
        }

        if (!user.getPassword().startsWith("$2a$")) {
            user.setPassword(passwordEncoder.encode(user.getPassword()));
        }

        user.setEnabled(true);
        User savedUser = userRepository.save(user);
        try {
            String subject = "Bienvenido a AulaMonitor - Su cuenta ha sido creada";
            String passwordText = isAutoGenerated ? "Contraseña temporal: " + rawPassword : "La contraseña que introdujo durante el registro.";

            String body = "Hola " + savedUser.getName() + ",\n\n" +
                    "Su cuenta en la plataforma AulaMonitor ha sido creada exitosamente.\n\n" +
                    "Sus credenciales de acceso son las siguientes:\n" +
                    "Usuario: " + savedUser.getEmail() + "\n" +
                    passwordText + "\n\n" +
                    "Le recomendamos que inicie sesión y cambie su contraseña lo antes posible.\n\n" +
                    "Saludos,\nEl equipo de AulaMonitor.";

            emailService.sendEmail(savedUser.getEmail(), subject, body);
        } catch (Exception e) {
            System.err.println("CRÍTICO: No se pudo enviar el correo de bienvenida a " + savedUser.getEmail() + ". Error: " + e.getMessage());
        }

        String actor = performingUser != null ? performingUser.getEmail() : "Sistema Automático";
        auditLogService.logAction(
                "USUARIO_CREADO",
                actor,
                "Se creó el usuario: " + savedUser.getEmail() + " con el rol de " + savedUser.getRole()
        );

        return savedUser;
    }

    @Transactional
    public User updateUser(String id, UserDTO userDTO, User performingUser) {
        User existingUser = getUserById(id);

        boolean isPerformingAdmin = performingUser.getRole() == Rol.ADMIN;
        boolean isPerformingCoordinator = performingUser.getRole() == Rol.COORDINADOR;
        boolean isSelf = existingUser.getId().equals(performingUser.getId());

        if (!isPerformingAdmin && !isSelf && !isPerformingCoordinator) {
            throw new UnauthorizedAccessException("No tienes permiso para actualizar este usuario.");
        }

        if (isPerformingCoordinator && !isSelf) {
            if (!CareerUtils.areSameCareerGroup(performingUser.getCareer(), existingUser.getCareer())) {
                throw new UnauthorizedAccessException("No puedes gestionar usuarios de otro grupo académico.");
            }
            if (existingUser.getRole() != Rol.ESTUDIANTE && existingUser.getRole() != Rol.PROFESOR && existingUser.getRole() != Rol.TUTOR) {
                throw new UnauthorizedAccessException("Solo puedes gestionar Estudiantes, Profesores o Tutores.");
            }
            if (userDTO.getCareer() != null && !userDTO.getCareer().equals(existingUser.getCareer())) {
                if (!CareerUtils.areSameCareerGroup(performingUser.getCareer(), userDTO.getCareer())) {
                    throw new UnauthorizedAccessException("No puedes cambiar al usuario a una carrera fuera de tu grupo.");
                }
            }
        }

        if (userDTO.getName() != null) {
            existingUser.setName(userDTO.getName());
        }

        if (userDTO.getEmail() != null && !existingUser.getEmail().equalsIgnoreCase(userDTO.getEmail())) {
            Optional<User> userWithNewEmail = userRepository.findByEmail(userDTO.getEmail());
            if (userWithNewEmail.isPresent() && !userWithNewEmail.get().getId().equals(existingUser.getId())) {
                throw new UserAlreadyExistsException("El nuevo correo electrónico ya está en uso.");
            }
            existingUser.setEmail(userDTO.getEmail());
        }

        if (userDTO.getCareer() != null) {
            existingUser.setCareer(userDTO.getCareer());
        }

        if (userDTO.getAvatarUrl() != null) {
            existingUser.setAvatarUrl(userDTO.getAvatarUrl().isEmpty() ? null : userDTO.getAvatarUrl());
        }

        if (userDTO.getRole() != null && userDTO.getRole() != existingUser.getRole()) {
            if (isPerformingAdmin) {
                if (isSelf && userDTO.getRole() != Rol.ADMIN) {
                    throw new UnauthorizedAccessException("Un administrador no puede quitarse su propio rol de admin.");
                }
                existingUser.setRole(userDTO.getRole());
            } else {
                throw new UnauthorizedAccessException("No tienes permiso para cambiar el rol.");
            }
        }

        if (userDTO.getEnabled() != null && existingUser.isEnabled() != userDTO.getEnabled()) {
            if (isPerformingAdmin || (isPerformingCoordinator && !isSelf)) {
                existingUser.setEnabled(userDTO.getEnabled());
                if (!userDTO.getEnabled()) {
                    reservationRepository.deleteAllByUserId(existingUser.getId());
                }
            } else if (isSelf) {
                throw new UnauthorizedAccessException("No puedes deshabilitar tu propia cuenta.");
            } else {
                throw new UnauthorizedAccessException("No tienes permiso para cambiar el estado.");
            }
        }

        User savedUser = userRepository.save(existingUser);

        auditLogService.logAction(
                "USUARIO_ACTUALIZADO",
                performingUser.getEmail(),
                "Se actualizó la información o permisos del usuario: " + savedUser.getEmail()
        );

        return savedUser;
    }

    @Transactional
    public User uploadUserProfilePicture(String userId, MultipartFile file, User performingUser) throws IOException {
        User userToUpdate = getUserById(userId);

        boolean isAdmin = performingUser.getRole() == Rol.ADMIN;
        boolean isCoordinator = performingUser.getRole() == Rol.COORDINADOR;
        boolean isSelf = userToUpdate.getId().equals(performingUser.getId());

        if (!isSelf && !isAdmin) {
            if (isCoordinator) {
                if (userToUpdate.getRole() != Rol.ESTUDIANTE && userToUpdate.getRole() != Rol.PROFESOR && userToUpdate.getRole() != Rol.TUTOR) {
                    throw new UnauthorizedAccessException("No tienes permiso para cambiar la foto de este usuario.");
                }
                if (!CareerUtils.areSameCareerGroup(performingUser.getCareer(), userToUpdate.getCareer())) {
                    throw new UnauthorizedAccessException("Usuario de otra carrera.");
                }
            } else {
                throw new UnauthorizedAccessException("No tienes permiso para cambiar la foto de este usuario.");
            }
        }

        if (file.getContentType() == null || !file.getContentType().startsWith("image/")) {
            throw new IllegalArgumentException("El archivo debe ser una imagen.");
        }

        userToUpdate.setProfilePicture(file.getBytes());
        userToUpdate.setImageType(file.getContentType());

        return userRepository.save(userToUpdate);
    }

    @Transactional
    public void updateUserPassword(String userId, String currentPassword, String newPassword, User performingUser) {
        User userToUpdate = getUserById(userId);
        boolean isAdmin = performingUser.getRole() == Rol.ADMIN;
        boolean isSelf = userToUpdate.getId().equals(performingUser.getId());

        if (!isSelf && !isAdmin) {
            throw new UnauthorizedAccessException("No tienes permiso para cambiar la contraseña de este usuario.");
        }

        if (isSelf) {
            if (currentPassword == null || currentPassword.isEmpty()){
                throw new IllegalArgumentException("La contraseña actual es requerida.");
            }
            if(!passwordEncoder.matches(currentPassword, userToUpdate.getPassword())) {
                throw new InvalidCredentialsException("La contraseña actual es incorrecta.");
            }
        }

        userToUpdate.setPassword(passwordEncoder.encode(newPassword));
        userRepository.save(userToUpdate);

        auditLogService.logAction(
                "CONTRASEÑA_MODIFICADA",
                performingUser.getEmail(),
                "Se cambió la contraseña de la cuenta: " + userToUpdate.getEmail()
        );
    }

    @Transactional
    public void deleteUser(String id, User performingUser) {
        User userToDelete = getUserById(id);

        boolean isAdmin = performingUser.getRole() == Rol.ADMIN;
        boolean isCoordinator = performingUser.getRole() == Rol.COORDINADOR;

        if (isAdmin) {
            if (userToDelete.getId().equals(performingUser.getId())) {
                throw new UnauthorizedAccessException("No puedes eliminarte a ti mismo.");
            }
        } else if (isCoordinator) {
            if (userToDelete.getRole() != Rol.ESTUDIANTE && userToDelete.getRole() != Rol.PROFESOR && userToDelete.getRole() != Rol.TUTOR) {
                throw new UnauthorizedAccessException("No tienes permiso para eliminar usuarios con rol: " + userToDelete.getRole());
            }
            if (!CareerUtils.areSameCareerGroup(performingUser.getCareer(), userToDelete.getCareer())) {
                throw new UnauthorizedAccessException("No puedes eliminar usuarios de otra carrera.");
            }
            if (userToDelete.getId().equals(performingUser.getId())) {
                throw new UnauthorizedAccessException("No puedes eliminarte a ti mismo.");
            }
        } else {
            throw new UnauthorizedAccessException("No tienes permiso para eliminar este usuario.");
        }

        try {
            String subject = "Aviso: Su cuenta ha sido eliminada - AulaMonitor";
            String body = "Hola " + userToDelete.getName() + ",\n\n" +
                    "Le informamos que su cuenta en la plataforma AulaMonitor ha sido eliminada permanentemente por la administración.\n\n" +
                    "Si considera que esto es un error, por favor contacte a su coordinador.\n\n" +
                    "Saludos,\nEl equipo de AulaMonitor.";
            emailService.sendEmail(userToDelete.getEmail(), subject, body);
        } catch (Exception e) {
            System.err.println("No se pudo enviar correo de eliminación a: " + userToDelete.getEmail());
        }

        String deletedEmail = userToDelete.getEmail();

        reservationRepository.deleteAllByUserId(id);
        userRepository.delete(userToDelete);

        auditLogService.logAction(
                "USUARIO_ELIMINADO",
                performingUser.getEmail(),
                "Se eliminó permanentemente de la base de datos la cuenta: " + deletedEmail
        );
    }

    @Transactional
    public String uploadUsersFromExcel(MultipartFile file, User performingUser) throws IOException {
        int successCount = 0;
        int errorCount = 0;
        List<String> errors = new ArrayList<>();
        DataFormatter formatter = new DataFormatter();

        try (Workbook workbook = new XSSFWorkbook(file.getInputStream())) {
            Sheet sheet = workbook.getSheetAt(0);

            for (Row row : sheet) {
                if (row.getRowNum() == 0) continue;

                try {
                    String name = formatter.formatCellValue(row.getCell(0)).trim();
                    String email = formatter.formatCellValue(row.getCell(1)).trim();
                    String roleStr = formatter.formatCellValue(row.getCell(2)).trim();
                    String career = formatter.formatCellValue(row.getCell(3)).trim();

                    if (name.isEmpty() || email.isEmpty() || roleStr.isEmpty()) continue;

                    UserDTO dto = new UserDTO();
                    dto.setName(name);
                    dto.setEmail(email);
                    dto.setRole(Rol.valueOf(roleStr.toUpperCase()));
                    dto.setCareer(career.isEmpty() ? null : career);

                    createUser(dto, performingUser);
                    successCount++;
                } catch (Exception e) {
                    errorCount++;
                    errors.add("Fila " + (row.getRowNum() + 1) + ": " + e.getMessage());
                }
            }
        }

        auditLogService.logAction(
                "CARGA_MASIVA_USUARIOS",
                performingUser.getEmail(),
                "Se ejecutó una carga masiva. Éxitos: " + successCount + " | Errores: " + errorCount
        );

        if (errorCount > 0) {
            String primerError = errors.isEmpty() ? "Error desconocido" : errors.get(0);
            return "Se cargaron " + successCount + " usuarios. Fallaron " + errorCount + " (Ej: " + primerError + ")";
        }
        return "Carga masiva exitosa: " + successCount + " usuarios creados y notificados por correo.";
    }
}